const ActionType = {
  CHANGE_LOADING_STATUS: `CHANGE_LOADING_STATUS`,
  CHANGE_COMMENT_SENDING_STATUS: `CHANGE_COMMENT_SENDING_STATUS`,
  CHANGE_AUTH_STATUS: `CHANGE_AUTH_STATUS`,
  CHANGE_CITY: `CHANGE_CITY`,
  CHANGE_ACTIVE_OFFER: `CHANGE_ACTIVE_OFFER`,
  CHANGE_SORT_TYPE: `CHANGE_SORT_TYPE`,
  CHANGE_AUTH_INFO: `CHANGE_AUTH_INFO`,
  LOAD_OFFERS: `LOAD_OFFERS`,
  LOAD_CITIES: `LOAD_CITIES`,
  LOAD_NEARBY: `LOAD_NEARBY`,
  LOAD_COMMENTS: `LOAD_COMMENTS`,
  SET_COMMENT_ERROR: `SET_COMMENT_ERROR`,
};

export default ActionType;
